version: 0.2

phases:
  install:
    commands:
      - echo install started on `date`
      - pip3 install flask
  build:
    commands:
      - echo Build started on `date`
      - python3 test_app.py
  post_build:
    commands:
      - echo post Build on `date`
artifacts:
  files:
    - main.py
    - appspec.yml
    - templates/Jenkins-page.html
    - scripts/after_install.sh
    - scripts/start_flask.sh
    - scripts/stop_flask.sh
    - scripts/stop_flask.py
